language: cpp

os:
  - linux
  - osx

osx_image: xcode7

compiler:
  - clang
  - gcc

notifications:
 email:
   on_success: change
   on_failure: always

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    wget --no-check-certificate https://cmake.org/files/v3.5/cmake-3.5.0-Linux-x86_64.tar.gz
      && cmake --version
      && tar -xzf cmake-3.5.0-Linux-x86_64.tar.gz
      && sudo cp -fR cmake-3.5.0-Linux-x86_64/* /usr
      && sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
      && sudo apt-get update -qq
      && sudo apt-get install -qq -y --force-yes gcc-5 g++-5
      && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
      && sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
      && sudo apt-get install python3
      && alias python=python3
      && cd ${TRAVIS_BUILD_DIR}
      && wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
      && tar xf lcov_1.13.orig.tar.gz
      && cd lcov-1.13/
      && sudo make install
      && cd ..;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      pip install cpp-coveralls;
    fi
  - gem install coveralls-lcov

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_SKIA_CMARK=Off ..

script:
  - make
  - test/directcmr_test
  - make test

after_success:
  - alias python=python3
  - cd ..
  - mkdir coverage
  - cd coverage
  - cmake -DCMAKE_BUILD_TYPE=Debug -DWITH_COVERAGE=On ..
  - make directcmr_test
  - cd test
  - ./directcmr_test
  - lcov --compat-libtool --directory . --capture --output-file coverage.info
  - coveralls-lcov coverage.info
